server:
  port: 5555

spring:
  application:
    name: API-Gate

  cloud:
    gateway:
      routes:
        - id: auth-service-app
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: microservice-api-2
          uri: lb://microservice-2
          predicates:
            - Path=/micro2/**
          filters:
            - RewritePath=/micro2/(?<segment>.*), /${segment}

        - id: property-service
          uri: lb://PROPERTYSERVICE
          predicates:
            - Path=/propertyservice/**
          filters:
            - RewritePath=/propertyservice/(?<segment>.*), /${segment}
